Lesson 7
Mikalaitru/mikalai-trukhanovich-jupiter pull request #2
Opened 2024-12-11 06:07 UTC by Mikalaitru

2024-12-11 11:08 UTC, veneta13 requested changes
Overall, great job on your assignment! There are just a few adjustments needed - please review the separate comments I’ve left.

2024-12-11 11:08 UTC, veneta13 commented on lesson-7/index.html
> +<style>
Great job incorporating CSS into your portfolio! For best practices, the `<style>` tag should be nested within the `<head>` tag.

2024-12-11 11:08 UTC, veneta13 commented on lesson-7/index.html
> +<body>
Please wrap the About, Experience and Connect sections within `<section>` elements and assign them appropriate `id`s (you can find an example in the homework assignment rubric).

2024-12-11 21:51 UTC, Mikalaitru reviewed
Hi 
I made some changes
Thank you for your support

2024-12-12 08:00 UTC, veneta13 approved these changes
Great work!

2024-12-12 15:51 UTC, merged